# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_yxy?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置 Mybatis
mybatis-plus:
  #  指定相应接口对应的xml文件所在目录
  mapper-locations: classpath:mapper/*.xml
  #  实体类所在包
  type-aliases-package: top.yxy.boot.mp.entity
  configuration:
    # mybatis开启驼峰式命名
    map-underscore-to-camel-case: true

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #调试时打印 SQL 语句
  global-config:
    db-config:
      logic-delete-field:  deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除的值 默认为1
      logic-not-delete-value: 0 # 逻辑未删除的值 默认为0

logging:
  level:
    top.yxy.boot.mp.mapper: debug

