spring:
  mail:
    host: smtp.qq.com  #邮件服务器
    username: 2917755602@qq.com
    password: xljysarroigsdfid
    protocol: smtp #发送邮件的协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.part: 465  #邮件发送端口
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8